export const GET_LOCATIONS = "GET_LOCATIONS";
export const GET_ERRORS = "GET_ERRORS";
export const GET_MESSAGES = "GET_MESSAGES";
export const CREATE_MESSAGES = "CREATE_MESSAGES";
export const USER_LOADING = "USER_LOADING";
export const USER_UPDATE = "USER_UPDATE";
export const USER_DELETE = "USER_DELETE";
export const USER_CHANGE_PASSWORD = "USER_CHANGE_PASSWORD";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const CLEAR_LOCATIONS = 'CLEAR_LOCATIONS';
export const UPLOAD_SUCESS = 'UPLOAD_SUCESS';
export const UPLOAD_FAIL = 'UPLOAD_FAIL';
export const UPLOADING = 'UPLOADING';
export const LOADING_DATA = 'LOADING_DATA';
export const GET_DETAILS = 'GET_DETAILS';
export const LOADING_DETAILS = 'LOADING_DETAILS';
export const DELETE_LOCATION = 'DELETE_LOCATION';
export const CENTER_MAP = 'CENTER_MAP';
export const SHOW_MAP = 'SHOW_MAP';
export const SHOW_DIALOG = 'SHOW_DIALOG';
export const NOTIFY = 'NOTIFY';
export const NOTIFY_FAIL = 'NOTIFY_FAIL';
export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";
export const DELETE_NOTIFICATIONS = "DELETE_NOTIFICATIONS";
export const NOTIFICATION_FAIL = "NOTIFICATION_FAIL";
export const NOTIFYING = "NOTIFYING";
export const VISUALIZE_NOTIFICATION = "VISUALIZE_NOTIFICATION";












