# Generated by Django 3.1.3 on 2020-11-11 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20201111_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='endimestamp',
            new_name='endTimestamp',
        ),
    ]
