# Generated by Django 3.1.3 on 2020-11-11 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20201111_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='placeid',
            new_name='placeId',
        ),
    ]
