# Generated by Django 3.1.3 on 2020-11-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='endimestamp',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='startTimestamp',
            field=models.CharField(max_length=100),
        ),
    ]
